wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/users.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/material/dns.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons2/angular.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/java.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons2/grafana.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/material/security.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/user_shield.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/fire.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-5/exchange_alt.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/diagram_project.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-5/globe_asia.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/network_wired.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/server.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-5/hdd.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome/microchip.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-5/hdd.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/cubes.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/docker.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/shield_virus.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/shield_heart.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/material/functions.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/rocket.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons2/rabbitmq_original.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/code_branch.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons2/apachekafka_original_wordmark.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-5/cogs.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-5/cogs.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/database.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/database.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons/mongodb.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/hive.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-5/stream.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/warehouse.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/searchengin.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-5/tools.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons/google_analytics.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/folder_tree.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/object_group.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/floppy_disk.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons2/elasticsearch.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/material/search.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/brain.puml
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons/redis.puml

wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/users.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/material/dns.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons2/angular.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/java.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons2/grafana.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/material/security.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/user_shield.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/fire.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-5/exchange_alt.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/diagram_project.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-5/globe_asia.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/network_wired.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/server.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-5/hdd.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome/microchip.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-5/hdd.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/cubes.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/docker.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/shield_virus.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/shield_heart.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/material/functions.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/rocket.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons2/rabbitmq_original.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/code_branch.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons2/apachekafka_original_wordmark.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-5/cogs.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-5/cogs.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/database.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/database.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons/mongodb.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/hive.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-5/stream.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/warehouse.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/searchengin.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-5/tools.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons/google_analytics.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/folder_tree.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/object_group.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/floppy_disk.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons2/elasticsearch.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/material/search.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/brain.png
wget https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons/redis.png
